version: 1
disable_existing_loggers: False
formatters:
  standart:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  error:
    format: "[%(asctime)s] [%(levelname)s] [PID %(process)d:%(processName)s] - %(name)s.%(funcName)s(): %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console_stdout:
    formatter: standart
    class: logging.StreamHandler
    stream: ext://sys.stdout
  console_stderr:
    formatter: standart
    class: logging.StreamHandler
    stream: ext://sys.stderr
  error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
  info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standart
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
loggers:
  uvicorn:
    level: INFO
    handlers: ["console_stdout", "error_file_handler"]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: ["console_stderr", "error_file_handler", "info_file_handler"]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: ["console_stdout", "error_file_handler"]
    propagate: no
  app:
    level: DEBUG
    handlers: ["console_stdout", "error_file_handler", "info_file_handler"]
    propagate: no

root:
  level: INFO
  handlers: ["console_stdout", "console_stderr", "error_file_handler"]
  propagate: no