server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4
  
api:
  docs_url: null              
  redoc_url: null
  
processing:
  max_workers: 8
  timeout: 600
  
logging:
  level: "INFO"
  
security:
  max_requests_per_minute: 100
  
environment: "production"